# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e36ded15db3559d7423fd0ae4054f5b431a17eee6f63bbc8177c8054d3f00def7398a1c57244b7ab220cc0801565a18e8827f07843604f887a27f2f5e736574
  twinword_key: <%= ENV['TWINWORD_KEY'] %>

test:
  secret_key_base: 7d4992f512abc79660881968d9737a01e29caa79f91d572cccf93df12fad83bfff53a41f0ec0d0d0547e9253657aa2e3891e13ca1723e7260bb30ec0ab2c1e71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twinword_key: <%= ENV['TWINWORD_KEY'] %>
